name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/96573011708/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider
          service_account: github-actions-service-account@my-project-1540367072726.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - id: deploy
        name: Use gcloud CLI
        run: >
          gcloud functions deploy airbnb-server
          --gen2
          --trigger-http
          --entry-point=api
          --runtime=nodejs20
          --memory=128MiB
          --region=us-west1
          --source=.
          --allow-unauthenticated
          --set-build-env-vars DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          --set-build-env-vars DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          --set-build-env-vars DATABASE_USER=${{ secrets.DATABASE_USER }}
          --set-build-env-vars DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          --set-env-vars DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          --set-env-vars DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          --set-env-vars DATABASE_USER=${{ secrets.DATABASE_USER }}
          --set-env-vars DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
